// <auto-generated />
using System;
using Digital.Ventures.Data.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digital.Ventures.Data.Migrations
{
    [DbContext(typeof(DigitalVenturesDbContext))]
    partial class DigitalVenturesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Digital.Ventures.Data.Core.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new { Id = new Guid("e7ab4813-12bb-4475-98c5-bc5160c6fd87"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Harry Kane" },
                        new { Id = new Guid("5b7ed2d5-d619-421b-800e-ad71dbdf8578"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "Egypt", Name = "Mohamed Salah" },
                        new { Id = new Guid("3c7dfc35-6118-458b-a68d-2c9e0b74e69c"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "Senegal", Name = "Sadio Mane" },
                        new { Id = new Guid("c9963db3-95d2-4599-856b-ea2702344e10"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "South Korea", Name = "Son Heung-Min" },
                        new { Id = new Guid("4fae94e2-9e61-4a7b-8623-b8df35e0e3d8"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Trent Alexander-Arnold" },
                        new { Id = new Guid("2a98ffba-4d14-4cba-8ec4-bcc72bd101bc"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Harry Maguire" },
                        new { Id = new Guid("45d6fca6-1ae0-4876-be79-bc706cb3375e"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Ben Chilwell" },
                        new { Id = new Guid("2f533d74-f741-47bb-9880-7c4e9fe1dd8f"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Ross Barkley" },
                        new { Id = new Guid("ea6f1a16-4412-478c-9e94-dcee296512a6"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Jack Grealish" },
                        new { Id = new Guid("7768331e-9cca-4347-a27e-1f42ce9b3e2e"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Tyrone Mings" },
                        new { Id = new Guid("a7aeb14c-4f5d-469c-8b55-83931b08f507"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Jack Tarkowski" },
                        new { Id = new Guid("ba17e1fa-22eb-4e03-9e5c-819afe0941e3"), BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Country = "England", Name = "Nick Pope" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
